# Generated by Django 3.2.11 on 2022-05-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.BigIntegerField()),
                ('Redgno', models.IntegerField()),
                ('Event', models.CharField(choices=[('Dance', 'Dance'), ('Song', 'Song'), ('Drama', 'Drama')], default='Song', max_length=20)),
            ],
        ),
    ]
