# Generated by Django 3.2.11 on 2022-02-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classical_Dance_Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=30)),
                ('dorigin', models.CharField(max_length=30)),
                ('dcost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Modern_Dance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=30)),
                ('morigin', models.CharField(max_length=30)),
                ('mcost', models.FloatField()),
            ],
        ),
    ]
