# Generated by Django 3.2.11 on 2022-02-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoApp', '0003_information2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info3', models.CharField(max_length=20)),
                ('details3', models.CharField(max_length=300)),
            ],
        ),
    ]
