# Generated by Django 3.2.11 on 2022-02-09 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfoApp', '0004_information3'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Information2',
            new_name='Informations2',
        ),
        migrations.RenameModel(
            old_name='Information3',
            new_name='Informations3',
        ),
    ]
