# Generated by Django 3.2.11 on 2022-05-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Age', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Course', models.CharField(max_length=30)),
                ('DOB', models.DateField()),
            ],
        ),
    ]
