# Generated by Django 3.2.11 on 2022-05-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.BigIntegerField()),
                ('Redgno', models.IntegerField()),
                ('Event', models.CharField(choices=[('dance', 'Dance'), ('song', 'Song'), ('drama', 'Drama')], default='dance', max_length=20)),
            ],
        ),
    ]
